#!/usr/bin/env python3
"""Fail when a crate with tests is named by no `ci.yml` filter (issue #280).

`ci.yml` has no unfiltered test job. A crate no `-p` / `--package` /
`--manifest-path` names never runs, and the #171 diff-scoped guard cannot
see that: it only asks about newly added tests. This is the crate-level
ratchet for that gap.

Does not invoke cargo. A crate "has tests" when any `src/**/*.rs` code line is
a `#[test]` attribute, optionally qualified by a module path. Comments and
string literals are masked before this check. It is "named" when a
`run_nonzero` / `cargo test` line in `ci.yml` contains `-p <crate>`,
`--package <crate>`, or
`--manifest-path .../<crate>/Cargo.toml`. A `cargo clippy` or `cargo build`
mention of the same manifest path does NOT count (#437): clippy proves
nothing about whether the crate's tests run, and crediting it let every test
lane for a crate be deleted while this checker kept calling it covered.

The allowlist is `<crate> = <reason>`, one per line, and the reason is
mandatory (#504). Not covering a crate is a decision, and a bare name records
that someone made one rather than what they decided -- the same discipline
`unlinted-crates.allowlist` has enforced since #439.

Usage:
    check_uncovered_crates.py --workflow .github/workflows/ci.yml \\
        --allowlist tests/ci/uncovered-crates.allowlist
    check_uncovered_crates.py --workflow ci.yml --write-allowlist PATH
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

# One tolerant `name = "..."` reader shared with the sibling guards: four
# hand-written copies of this pattern drifted apart, and the two fixes the
# oldest copy received never reached the others (#494).
from toml_package_name import package_name

_ATTRIBUTE_PATH = re.compile(
    r"^\s*#\s*\[\s*(?P<path>[^\(\]]+?)(?=\s*(?:\(|\]))", re.MULTILINE
)
_RUST_RAW_STRING_START = re.compile(r'(?:br|cr|r)(?P<hashes>#+)?"')
_RUST_CHAR_LITERAL = re.compile(r"'(?:\\.|[^\\'\n])'")
_P_FLAG = re.compile(r"(?:^|[\s\\])(?:-p|--package)\s+([A-Za-z0-9][A-Za-z0-9_-]*)")
_MANIFEST = re.compile(r"--manifest-path\s+(\S+)")
# A line actually invokes the test binary. Same test as
# `check_test_filter_coverage.py`'s `_RUNNER`, kept separate rather than
# imported: this script's contract is "reads ci.yml text, never invokes
# cargo," and importing from a script that does invoke cargo would blur that.
_TEST_INVOCATION = re.compile(r"\b(?:run_nonzero|cargo test)\b")

# `third_party` was missing until #495: four real workspace members live
# there and were invisible to this guard's corpus, silently -- not as a
# reported gap, since a crate this scan never walks cannot become one. Two
# of them (dagre_rust, mermaid-to-svg) had real `src/` tests running in no
# `ci.yml` lane, undetected because the guard could not see the directory
# they were in, not because it saw them and cleared them.
_CRATE_ROOTS = ("crates", "prod", "third_party")

_ALLOWLIST_HEADER = """\
# Crates with src/ tests that no ci.yml -p / --manifest-path names (issue #280).
#
# Format: `<crate-name> = <reason>`. The reason is mandatory (#504). The
# sibling `unlinted-crates.allowlist` has required one since #439; this file
# recorded the same kind of decision -- *this crate is deliberately not
# covered* -- with the reason left out, and a bare name records that someone
# acted, not what they decided.
#
# Being listed here is NOT a claim that the crate does not need testing, and
# NOT a claim that its tests pass. It says only that no ci.yml lane runs them,
# and why that was accepted.
#
# `upstream-only` is a measurement with a method, not a judgement: no commit
# in `origin/main..providers` that is neither a merge nor an upstream sync
# touches the crate's directory, on the date given. Where that is not true the
# entry says what the fork wrote, because "upstream crate, upstream's tests"
# is the reading a bare name invites, and at the 2026-08-25 migration it was
# wrong for about a quarter of this list -- most of those carrying #33
# credential-redaction work, the fork's sharpest divergence. That proportion
# is a fact about the migration, not a running count: this header is rewritten
# verbatim by --write-allowlist, so a number here could not stay true.
#
# Shrinking this list is good. Growing it means a new crate's tests run nowhere.
# First burn-down targets: xai-grok-secrets and xai-chat-state.
# Generated by scripts/check_uncovered_crates.py --write-allowlist, which
# carries the reasons on surviving entries forward.
"""

_BOOTSTRAP_REASON = "tests run in no ci.yml lane; not yet triaged"


@dataclass(frozen=True)
class Crate:
    name: str
    dir_name: str
    manifest: Path


class AllowlistError(ValueError):
    """A malformed allowlist line -- notably a missing reason."""


@dataclass(frozen=True)
class Report:
    has_tests: frozenset[str]
    named: frozenset[str]
    allowlisted: frozenset[str]
    new_gaps: frozenset[str]
    stale: frozenset[str]


def _skip_literal_suffix(source: str, index: int) -> int:
    """Consume an identifier suffix attached to a Rust literal token."""

    if index >= len(source) or not source[index].isidentifier():
        return index
    index += 1
    while index < len(source) and ("a" + source[index]).isidentifier():
        index += 1
    return index


def _skip_quoted(source: str, index: int) -> int:
    index += 1
    while index < len(source):
        if source[index] == "\\":
            index += 2
        elif source[index] == '"':
            return _skip_literal_suffix(source, index + 1)
        else:
            index += 1
    return len(source)


def _skip_raw_string(source: str, index: int) -> int | None:
    match = _RUST_RAW_STRING_START.match(source, index)
    if not match:
        return None
    if index:
        previous = source[index - 1]
        # A raw prefix is a token start, not a suffix inside an identifier or
        # lifetime.  Without this boundary, valid `'r"..."` token adjacency
        # is mistaken for a raw string beginning at the lifetime's `r`.
        if previous == "'" or ("a" + previous).isidentifier():
            return None
    hashes = match.group("hashes") or ""
    terminator = '"' + hashes
    end = source.find(terminator, match.end())
    if end < 0:
        return len(source)
    return _skip_literal_suffix(source, end + len(terminator))


def _skip_comment(source: str, index: int) -> int | None:
    if source.startswith("//", index):
        end = source.find("\n", index + 2)
        return len(source) if end < 0 else end
    if not source.startswith("/*", index):
        return None

    depth = 1
    cursor = index + 2
    while cursor < len(source) and depth:
        if source.startswith("/*", cursor):
            depth += 1
            cursor += 2
        elif source.startswith("*/", cursor):
            depth -= 1
            cursor += 2
        else:
            cursor += 1
    return cursor


def _code_only(source: str) -> str:
    """Mask Rust comments and literals while retaining line boundaries."""

    result = list(source)
    index = 0
    while index < len(source):
        end = _skip_comment(source, index)
        if end is None:
            end = _skip_raw_string(source, index)
        if end is None and source[index] == '"':
            end = _skip_quoted(source, index)
        if end is None and source[index] == "'":
            match = _RUST_CHAR_LITERAL.match(source, index)
            end = _skip_literal_suffix(source, match.end()) if match else None
        if end is None:
            index += 1
            continue
        for masked in range(index, end):
            if result[masked] != "\n":
                result[masked] = " "
        index = end
    return "".join(result)


def _has_test_attribute(code: str) -> bool:
    """Whether a code-only Rust source contains an attribute ending in `test`."""

    for match in _ATTRIBUTE_PATH.finditer(code):
        path = "".join(match.group("path").split())
        if path.startswith("::"):
            path = path[2:]
        segments = path.split("::")
        identifiers: list[str] = []
        for segment in segments:
            identifier = segment[2:] if segment.startswith("r#") else segment
            if not identifier.isidentifier():
                break
            identifiers.append(identifier)
        else:
            if identifiers and identifiers[-1] == "test":
                return True
    return False


def iter_crates(root: Path) -> list[Crate]:
    found: list[Crate] = []
    for base in _CRATE_ROOTS:
        base_dir = root / base
        if not base_dir.is_dir():
            continue
        for manifest in sorted(base_dir.rglob("Cargo.toml")):
            try:
                text = manifest.read_text(encoding="utf-8")
            except (OSError, UnicodeDecodeError):
                continue
            name = package_name(text)
            if name is None:
                continue
            found.append(Crate(name=name, dir_name=manifest.parent.name, manifest=manifest))
    return found


def src_has_tests(crate_dir: Path) -> bool:
    src = crate_dir / "src"
    if not src.is_dir():
        return False
    for rs in src.rglob("*.rs"):
        try:
            text = rs.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        if _has_test_attribute(_code_only(text)):
            return True
    return False


def named_tokens(workflow_text: str) -> set[str]:
    """Crate names a `run_nonzero` / `cargo test` line names via `-p` /
    `--package` / `--manifest-path`.

    A `cargo clippy` or `cargo build` mention does NOT count (#437): every
    test lane for a crate can be deleted while a clippy step still names its
    manifest path, and that left this checker calling the crate "covered"
    with nothing left to run its tests -- invisible to this ratchet, and
    deferred right past by `check_test_filter_coverage.py`'s own `#280`
    hand-off, so neither guard saw the hole. Joins line continuations first,
    matching `check_test_filter_coverage.py`'s `_parse_workflow`: `ci.yml`
    wraps long invocations with a trailing backslash, and the flag is
    usually on the continuation line.
    """
    joined = re.sub(r"\\\s*\n\s*", " ", workflow_text)
    names: set[str] = set()
    for line in joined.splitlines():
        if not _TEST_INVOCATION.search(line):
            continue
        names.update(_P_FLAG.findall(line))
        for raw in _MANIFEST.findall(line):
            path = raw.strip().strip("'\"")
            parent = Path(path).parent.name
            if parent:
                names.add(parent)
    return names


def crate_is_named(crate: Crate, tokens: set[str]) -> bool:
    return crate.name in tokens or crate.dir_name in tokens


def load_allowlist(path: Path) -> dict[str, str]:
    """`<crate> = <reason>` per line. A missing reason is an error, not a default.

    Mirrors `check_unlinted_crates.py`'s loader, for the reason #504 gives:
    both files record *this crate is deliberately not covered*, and only one
    of them used to record why. Kept as a second implementation rather than
    an import -- this script's contract is "reads ci.yml text, never invokes
    cargo", and the two files share no other code today.
    """
    entries: dict[str, str] = {}
    for lineno, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        name, sep, reason = line.partition("=")
        name, reason = name.strip(), reason.strip()
        if not sep or not name:
            raise AllowlistError(
                f"{path}:{lineno}: expected `<crate> = <reason>`, got {raw!r}"
            )
        if not reason:
            raise AllowlistError(
                f"{path}:{lineno}: {name} has no reason. An exemption without a "
                f"written justification becomes permanent by default."
            )
        entries[name] = reason
    return entries


def read_reasons(path: Path) -> dict[str, str]:
    """Best-effort `<crate> = <reason>` read, for the rewrite path only.

    Deliberately lenient where `load_allowlist` is strict: `--write-allowlist`
    is the tool that *repairs* a malformed file, so it must be able to read one
    -- including the names-only file this format replaced. A line it cannot
    parse contributes no reason and the entry is re-bootstrapped, which shows
    up as a diff someone reviews. The verifying path stays strict, so a file
    that only this function can read still fails CI.
    """
    reasons: dict[str, str] = {}
    if not path.exists():
        return reasons
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        name, sep, reason = line.partition("=")
        if sep and name.strip() and reason.strip():
            reasons[name.strip()] = reason.strip()
    return reasons


def evaluate(
    *,
    root: Path,
    workflow_text: str,
    allowlisted: dict[str, str],
) -> Report:
    crates = iter_crates(root)
    tokens = named_tokens(workflow_text)
    has_tests = frozenset(c.name for c in crates if src_has_tests(c.manifest.parent))
    covered = set(tokens)
    for crate in crates:
        if crate_is_named(crate, tokens):
            covered.add(crate.name)
            covered.add(crate.dir_name)
    allow = frozenset(allowlisted)
    return Report(
        has_tests=has_tests,
        named=frozenset(tokens),
        allowlisted=allow,
        new_gaps=frozenset(has_tests - covered - allow),
        stale=frozenset(allow & covered),
    )


def format_report(report: Report) -> str:
    lines = [
        f"has-tests: {len(report.has_tests)}",
        f"named: {len(report.named)}",
        f"allowlisted: {len(report.allowlisted)}",
        f"new-gaps: {len(report.new_gaps)}",
    ]
    for name in sorted(report.new_gaps):
        lines.append(
            f"new gap: {name} (has tests, not named in ci.yml, not allowlisted)"
        )
    for name in sorted(report.stale):
        lines.append(
            f"stale allowlist: {name} (now named in ci.yml; remove it)"
        )
    if not report.new_gaps and not report.stale:
        lines.append("ok: every crate with tests is named in ci.yml or allowlisted")
    return "\n".join(lines) + "\n"


def write_allowlist(
    path: Path, uncovered: set[str], existing: dict[str, str] | None = None
) -> None:
    """Rewrite `path`, carrying the reason on every surviving entry forward.

    Without the carry-forward a single `--write-allowlist` run would replace
    every hand-written justification with the bootstrap placeholder -- the
    reasons #504 added, erased by the tool that maintains the file, silently
    and with a plausible-looking diff.
    """
    existing = existing or {}
    path.parent.mkdir(parents=True, exist_ok=True)
    body = _ALLOWLIST_HEADER + "".join(
        f"{name} = {existing.get(name, _BOOTSTRAP_REASON)}\n"
        for name in sorted(uncovered)
    )
    path.write_text(body, encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--workflow", required=True, type=Path)
    ap.add_argument("--root", type=Path, default=Path("."))
    ap.add_argument(
        "--allowlist",
        type=Path,
        default=None,
        help="crate names already uncovered; only NEW gaps fail",
    )
    ap.add_argument(
        "--write-allowlist",
        type=Path,
        default=None,
        help="write the current uncovered set and exit 0",
    )
    args = ap.parse_args(argv)

    try:
        workflow_text = args.workflow.read_text(encoding="utf-8")
    except OSError as exc:
        print(f"error: cannot read workflow: {exc}", file=sys.stderr)
        return 2

    if not named_tokens(workflow_text):
        print(
            "error: no -p / --package / --manifest-path crate names in the "
            "workflow -- has ci.yml's shape changed?",
            file=sys.stderr,
        )
        return 2

    allowlisted: dict[str, str] = {}
    if args.allowlist is not None:
        if not args.allowlist.exists():
            print(f"error: allowlist not found: {args.allowlist}", file=sys.stderr)
            return 2
        try:
            allowlisted = load_allowlist(args.allowlist)
        except AllowlistError as error:
            # 2, not 1: this file's own convention separates "could not
            # evaluate" from "evaluated, and the answer is a gap". The sibling
            # guard returns 1 because it has no such split. Either way the
            # step fails; the distinction is for whoever reads the log.
            print(f"error: {error}", file=sys.stderr)
            return 2

    report = evaluate(
        root=args.root,
        workflow_text=workflow_text,
        allowlisted=allowlisted,
    )

    if not report.has_tests:
        print(
            "error: no crates with src/ tests under crates/ or prod/ -- "
            "has the tree shape changed?",
            file=sys.stderr,
        )
        return 2

    if args.write_allowlist is not None:
        # Empty allowlist so new_gaps is today's full uncovered set, including
        # crates only covered via a --manifest-path directory name.
        current = evaluate(
            root=args.root,
            workflow_text=workflow_text,
            allowlisted={},
        )
        write_allowlist(
            args.write_allowlist,
            set(current.new_gaps),
            read_reasons(args.write_allowlist),
        )
        print(f"wrote {len(current.new_gaps)} entries to {args.write_allowlist}")
        return 0

    sys.stdout.write(format_report(report))
    return 1 if report.new_gaps or report.stale else 0


if __name__ == "__main__":
    sys.exit(main())
