#!/usr/bin/env python3
"""Fail when a workspace crate the clippy job does not lint is not allowlisted (#439).

`ci.yml`'s clippy job names its crates one `--manifest-path` at a time, with the
reasoning recorded above it: full-workspace clippy is too slow, and no `-A`
allow-list because that would re-open the blind spot the job exists to close.

The `-A` reasoning is right and the crate list is the same blind spot in a
different coordinate. A crate that is not named is not linted, nothing reports
that it is not named, and nothing reports when an unnamed crate starts failing
-- which is how `xai-grok-workspace` sat with three clippy errors while
`providers` looked green.

This is the ratchet. It does not lint anything and does not argue for linting
everything: not linting a crate simply has to be a recorded decision rather
than an omission nobody can see.

Deliberately unlike `check_uncovered_crates.py` (#280), which counts a crate as
covered when *any* `-p` in the file mentions it. Here a mention is not enough:
an invocation only counts when it carries **both** `--all-targets` and
`-D warnings`. A `--lib`-only clippy never sees test or bench targets -- that is
exactly how `.err().expect()` lived green in `xai-grok-pager-bin` -- and without
`-D warnings` nothing fails. Counting a weaker invocation would move this job's
blind spot inside the instrument meant to close it.

No Rust toolchain and no YAML parser: this reads the workspace manifest,
each member's `Cargo.toml`, `ci.yml`, and a checked-in allowlist.

Usage:
    check_unlinted_crates.py --workflow .github/workflows/ci.yml \\
        --allowlist tests/ci/unlinted-crates.allowlist
    check_unlinted_crates.py --workflow ci.yml --write-allowlist PATH
"""

from __future__ import annotations

import argparse
import re
import shlex
import sys
from dataclasses import dataclass
from pathlib import Path

# The tolerant `[package] name` reader, shared with the sibling guards.
# This file had its own copy: the comment tolerance (#464) and the quoted
# key (#486) were both fixed here and reached none of the other three,
# which is the drift #494 collapses. Its table-header handling had the
# same gap in the other direction -- `[package] # metadata` was never
# entered and `[features] # x` never left.
from toml_package_name import package_name

_MEMBERS_BLOCK = re.compile(r"^members\s*=\s*\[(.*?)^\]", re.MULTILINE | re.DOTALL)
_QUOTED = re.compile(r"""["']([^"']+)["']""")
_MANIFEST = re.compile(r"--manifest-path\s+(\S+)")
_P_FLAG = re.compile(r"(?:^|[\s\\])(?:-p|--package)\s+([A-Za-z0-9][A-Za-z0-9_-]*)")
_ENV_ASSIGNMENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*=")
# GHA `run:` may be a list item (`- run:`) or a mapping on a named step
# (`run:` with no leading dash). YAML quoting is stripped before the shell
# sees the value (#508 review).
_YAML_RUN = re.compile(r"^(?:-\s+)?run:\s+(.*)$")

# A crate the workspace declares but whose manifest cannot be read is a bug in
# this script or a broken tree, never a silent pass.
_MIN_PLAUSIBLE_CRATES = 20

_ALLOWLIST_HEADER = """\
# Workspace crates the ci.yml clippy job does not lint (issue #439).
#
# Format: `<crate-name> = <reason>`. The reason is mandatory -- an exemption
# whose justification is not written down becomes permanent by default, which
# is the failure mode this whole family of guards exists to prevent.
#
# `never linted at deny level; not yet triaged` means exactly that: the crate
# has never been in the clippy job, so nobody knows whether it is clean. It is
# not a claim that the crate is clean. Triaging these is #457; the PR that
# introduced this file carries the per-crate table #457 was scoped from.
#
# Shrinking this list is good. Growing it means a crate stopped being linted.
# Generated by scripts/check_unlinted_crates.py --write-allowlist.
"""

_BOOTSTRAP_REASON = "never linted at deny level; not yet triaged"


@dataclass(frozen=True)
class Crate:
    name: str
    dir_name: str
    manifest: Path


@dataclass(frozen=True)
class Report:
    crates: tuple[str, ...]
    linted: frozenset[str]
    allowlisted: frozenset[str]
    new_gaps: frozenset[str]
    stale: frozenset[str]
    unknown: frozenset[str]

    @property
    def ok(self) -> bool:
        return not (self.new_gaps or self.stale or self.unknown)


class AllowlistError(ValueError):
    """A malformed allowlist line -- notably a missing reason."""


def workspace_member_dirs(root: Path) -> list[str]:
    """Member paths from the root manifest's `[workspace] members`."""
    text = (root / "Cargo.toml").read_text(encoding="utf-8")
    block = _MEMBERS_BLOCK.search(text)
    if block is None:
        return []
    return _QUOTED.findall(block.group(1))


def iter_crates(root: Path) -> list[Crate]:
    """Every workspace member that declares a `[package]`."""
    found: list[Crate] = []
    for member in workspace_member_dirs(root):
        manifest = root / member / "Cargo.toml"
        try:
            text = manifest.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        name = package_name(text)
        if name is None:
            continue
        found.append(Crate(name=name, dir_name=Path(member).name, manifest=manifest))
    return found


def _strip_shell_comments(workflow_text: str) -> str:
    """Drop bash comments from each physical line before anything else runs.

    A `cargo clippy` invocation disabled by prefixing it with `#` must not be
    counted as linting anything -- that is the exact blind spot this guard
    exists to close, just moved one layer down (#439 follow-up). This has to
    happen *before* the line-continuation join below: in bash, `#` comments
    to the end of the physical line, and a trailing `\\` inside a comment does
    not continue it, so joining first would let a commented-out line absorb
    the next real command.

    A full-line comment is dropped entirely; a trailing inline comment is
    truncated so flag spellings that only appear in prose (e.g. describing
    `--all-targets` in an explanatory comment) cannot be counted as though
    the command carried them.
    """
    lines = []
    for raw_line in workflow_text.splitlines():
        if raw_line.strip().startswith("#"):
            continue
        lines.append(re.sub(r"#.*$", "", raw_line))
    return "\n".join(lines)


@dataclass(frozen=True)
class LintedInvocationTokens:
    """Tokens a deny-level `cargo clippy` invocation names, kept apart by kind.

    `-p`/`--package` names a *package*; `--manifest-path` names a *directory*.
    Those are different namespaces that can collide -- a crate's package name
    can equal a different crate's directory basename, or vice versa. Folding
    both into one set (as `linted_tokens()` below still does, for its own
    tested contract) would let that collision cross-credit the wrong crate as
    linted; `evaluate()` matches each kind only against its own namespace to
    close that (#439 follow-up).
    """

    manifest_dirs: frozenset[str]
    package_names: frozenset[str]


def linted_invocation_tokens(workflow_text: str) -> LintedInvocationTokens:
    """Extract `--manifest-path` directories and `-p`/`--package` names separately.

    Both `--all-targets` and `-D warnings` are required; see the module
    docstring for why a weaker invocation must not count.

    Matching is literal, so a spelling this does not know (`-Dwarnings`,
    `--deny warnings`) reads as "not linted". That direction is deliberate:
    the guard then demands an allowlist entry, which is a visible diff someone
    reviews, rather than quietly accepting an invocation it did not understand.

    The same direction disqualifies any line carrying a `;`, `&`, or `|`
    after `-D warnings`' text is matched: those are the shell operators that
    can mask or discard `cargo clippy`'s exit status (`|| true`, `|| :`,
    `; true`, `&& true`) or hide it behind a pipe (`| tee`, `2>&1 | tee`) --
    the same blind spot as a commented-out line (#439 follow-up), just via
    a live command whose failure never reaches the shell's own exit code.
    A whitelist of exact patterns would miss spellings it does not
    enumerate; disqualifying the operators themselves does not need to. This
    also makes a per-step `set -o pipefail` correlation unnecessary: a piped
    invocation is disqualified regardless of whether pipefail is on. The one
    cost is `2>&1` alone (no pipe) also disqualifies, since it contains `&`
    -- accepted deliberately, in the same direction as everything else here.

    `set +e` and a step's `continue-on-error: true` can have the same
    effect but are not on this line -- the first is shell state carried from
    elsewhere in the same step, the second is a YAML key on the step, not
    the command. Both would need step-boundary parsing this script
    deliberately does not do (see the module docstring); they are not
    checked here.

    `"cargo clippy" in line` is not enough: `echo cargo clippy ...`
    contains those words and never lints. After comment-stripping and
    continuation-joining, a single-line GitHub Actions `- run:` is reduced
    to the command GitHub actually execs (YAML quoting stripped -- a quoted
    `'cargo clippy ...'` is one YAML scalar whose quotes never reach argv)
    and then `shlex`-split so `cargo`/`clippy` occupy the command position
    (after optional `NAME=value` assignments). A diagnostic print of the
    command must not count as a deny-level invocation (#508 review).
    """
    commentless = _strip_shell_comments(workflow_text)
    joined = re.sub(r"\\\s*\n\s*", " ", commentless)
    manifest_dirs: set[str] = set()
    package_names: set[str] = set()
    for line in joined.splitlines():
        shell = _workflow_shell_line(line)
        if "--all-targets" not in shell or "-D warnings" not in shell:
            continue
        if any(op in shell for op in (";", "&", "|")):
            continue
        try:
            tokens = shlex.split(shell)
        except ValueError:
            continue
        if not _is_cargo_clippy_argv(tokens):
            continue
        for raw in _MANIFEST.findall(shell):
            parent = Path(raw.strip().strip("'\"")).parent.name
            if parent:
                manifest_dirs.add(parent)
        package_names.update(_P_FLAG.findall(shell))
    return LintedInvocationTokens(
        manifest_dirs=frozenset(manifest_dirs), package_names=frozenset(package_names)
    )


def _unquote_yaml_flow_scalar(value: str) -> str:
    """Strip YAML quoting Actions applies before the shell sees `run:`.

    A quoted `- run: 'cargo clippy ...'` is one YAML scalar. `shlex.split`
    on the raw line then yields a single token for the whole command, so
    `cargo` never occupies the command position and a real deny-level
    invocation is missed (#508 review).
    """
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] == "'":
        return value[1:-1].replace("''", "'")
    if len(value) >= 2 and value[0] == value[-1] == '"':
        inner = value[1:-1]
        return inner.replace(r"\\", "\0").replace(r"\"", '"').replace("\0", "\\")
    return value


def _workflow_shell_line(line: str) -> str:
    """The command a GHA `run:` scalar actually execs, else the line as-is."""
    match = _YAML_RUN.match(line.lstrip())
    if match:
        return _unquote_yaml_flow_scalar(match.group(1))
    return line


def _is_cargo_clippy_argv(tokens: list[str]) -> bool:
    """True when `cargo clippy` is the invoked command, not a substring.

    A single-line GitHub Actions `run:` is valid workflow syntax
    (`- run: cargo clippy ...`). After `shlex.split` the YAML tokens `-`
    and `run:` sit in front of `cargo`; skipping them is what keeps a
    real deny-level invocation from looking like `echo cargo clippy`
    (#508 review).
    """
    i = 0
    while i < len(tokens) and tokens[i] in ("-", "run:"):
        i += 1
    while i < len(tokens) and _ENV_ASSIGNMENT.match(tokens[i]):
        i += 1
    return i + 1 < len(tokens) and tokens[i] == "cargo" and tokens[i + 1] == "clippy"


def linted_tokens(workflow_text: str) -> set[str]:
    """Every crate- or directory-shaped token a deny-level invocation names.

    This is the union of `linted_invocation_tokens()`'s two kinds, with their
    provenance erased. `evaluate()` does not use this -- it needs to know
    which namespace each token came from, precisely to avoid the collision
    described on `LintedInvocationTokens`. This stays a separate, tested
    function because "what does this invocation mention, of any kind" is
    still a useful question on its own.
    """
    kinds = linted_invocation_tokens(workflow_text)
    return set(kinds.manifest_dirs) | set(kinds.package_names)


def load_allowlist(path: Path) -> dict[str, str]:
    """`<crate> = <reason>` per line. A missing reason is an error, not a default."""
    entries: dict[str, str] = {}
    for lineno, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        name, sep, reason = line.partition("=")
        name, reason = name.strip(), reason.strip()
        if not sep or not name:
            raise AllowlistError(
                f"{path}:{lineno}: expected `<crate> = <reason>`, got {raw!r}"
            )
        if not reason:
            raise AllowlistError(
                f"{path}:{lineno}: {name} has no reason. An exemption without a "
                f"written justification becomes permanent by default."
            )
        entries[name] = reason
    return entries


def evaluate(
    *,
    root: Path,
    workflow_text: str,
    allowlisted: dict[str, str],
) -> Report:
    crates = iter_crates(root)
    names = frozenset(c.name for c in crates)
    tokens = linted_invocation_tokens(workflow_text)

    # `-p`/`--package` only ever names a package; `--manifest-path` only ever
    # names a directory. Checking a crate's name against the manifest-path
    # set (or its directory against the package-name set) would credit it
    # for an invocation that was never about it (#439 follow-up).
    linted = {
        c.name
        for c in crates
        if c.name in tokens.package_names or c.dir_name in tokens.manifest_dirs
    }
    allow = frozenset(allowlisted)
    return Report(
        crates=tuple(sorted(names)),
        linted=frozenset(linted),
        allowlisted=allow,
        new_gaps=frozenset(names - linted - allow),
        stale=frozenset(allow & linted),
        unknown=frozenset(allow - names),
    )


def format_report(report: Report) -> str:
    lines = [
        f"workspace crates: {len(report.crates)}",
        f"linted at deny level: {len(report.linted)}",
        f"allowlisted: {len(report.allowlisted)}",
        f"new gaps: {len(report.new_gaps)}",
    ]
    for name in sorted(report.new_gaps):
        lines.append(
            f"new gap: {name} (workspace crate, not linted by ci.yml, not allowlisted)"
        )
    for name in sorted(report.stale):
        lines.append(f"stale allowlist: {name} (now linted by ci.yml; remove it)")
    for name in sorted(report.unknown):
        lines.append(f"unknown allowlist entry: {name} (not a workspace crate; remove it)")
    if report.ok:
        lines.append("ok: every workspace crate is linted by ci.yml or allowlisted")
    return "\n".join(lines) + "\n"


def write_allowlist(path: Path, unlinted: set[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    body = _ALLOWLIST_HEADER + "".join(
        f"{name} = {_BOOTSTRAP_REASON}\n" for name in sorted(unlinted)
    )
    path.write_text(body, encoding="utf-8")


def _implausible_corpus_error(crate_count: int, root: Path) -> str | None:
    """`None` if `crate_count` clears `_MIN_PLAUSIBLE_CRATES`, else the error text.

    An empty or implausibly small corpus means the manifest parse broke, not
    that the workspace shrank -- without this, a broken parse reports "no
    crates, no gaps, ok", the exact green that proves the opposite of what it
    claims. Every path that acts on `evaluate()`'s crate count, not only the
    one that prints a verdict, must check this before acting: `--write-allowlist`
    used to check only on the report path, so a degraded corpus could be
    written over the tracked allowlist as fact, silently erasing the
    exemptions for every crate the parse failed to see (#439 follow-up).
    """
    if crate_count >= _MIN_PLAUSIBLE_CRATES:
        return None
    return (
        f"error: found only {crate_count} workspace crates under {root}; "
        f"expected at least {_MIN_PLAUSIBLE_CRATES}. The `[workspace] "
        f"members` parse is broken, not the workspace."
    )


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--workflow", required=True, type=Path)
    ap.add_argument("--root", type=Path, default=Path("."))
    ap.add_argument("--allowlist", type=Path, default=None)
    ap.add_argument(
        "--write-allowlist",
        type=Path,
        default=None,
        help="write the current unlinted set and exit 0",
    )
    args = ap.parse_args(argv)

    workflow_text = args.workflow.read_text(encoding="utf-8")

    if args.write_allowlist is not None:
        report = evaluate(root=args.root, workflow_text=workflow_text, allowlisted={})
        error = _implausible_corpus_error(len(report.crates), args.root)
        if error is not None:
            print(error, file=sys.stderr)
            return 1
        write_allowlist(args.write_allowlist, set(report.new_gaps))
        print(f"wrote {len(report.new_gaps)} entries to {args.write_allowlist}")
        return 0

    try:
        allowlisted = load_allowlist(args.allowlist) if args.allowlist else {}
    except AllowlistError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    report = evaluate(
        root=args.root, workflow_text=workflow_text, allowlisted=allowlisted
    )

    error = _implausible_corpus_error(len(report.crates), args.root)
    if error is not None:
        print(error, file=sys.stderr)
        return 1

    sys.stdout.write(format_report(report))
    return 0 if report.ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
